# Generated by Django 2.0.5 on 2018-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180517_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
