# Generated by Django 2.0.5 on 2018-05-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180518_1246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('episode_number', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('season_number', 'show')},
        ),
    ]
